version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ludgi-prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Prometheus 설정 파일 매핑
    ports:
      - "9090:9090" # Prometheus 외부 포트
    networks:
      - ludgi-network

  grafana:
    image: grafana/grafana:latest
    container_name: ludgi-grafana
    restart: always
    environment:
      - GF_SERVER_HTTP_PORT=4000 # Grafana 내부 포트를 4000으로 설정
      - GF_SECURITY_ADMIN_USER=admin # Grafana 관리자 사용자 이름
      - GF_SECURITY_ADMIN_PASSWORD=test123! # Grafana 관리자 비밀번호
    ports:
      - "8081:4000" # 외부 8081 → 내부 4000 매핑
    networks:
      - ludgi-network

networks:
  ludgi-network:
    name: ludgi-network
