version: '3.9'

services:
  postgres_db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_db
    restart: always
    shm_size: 128mb
    networks:
      - ludgi-network
    ports:
      - "9915:5432"
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres # must change your own password.
      POSTGRES_USER: postgres # should change yout own user name.
      # POSTGRES_DB: mydatabase # Not required if you use prisma.

networks:
  ludgi-network:
    name: ludgi-network

volumes:
  postgres_db_volume:
    name: postgres_db_volume
